### ISSUE TITLE
ripple animation unreliable on Chrome mobile

### ISSUE THREAD

**Issue by jptrainor** [PolymerElements/paper-radio-button#84] opened 2016-02-06 13:02 UTC
I'm having trouble with paper-radio-button ripple animations not completing on Chrome mobile. It is fine with Desktop Chrome.  The demo page has the same problems I see in my own application.  Touch the radio button and the animation does not always complete.  A long touch seems to help but even that is not totally reliable (and it is an abnormal interaction, so not helpful beyond understanding the problem).

A possibly related issue is that the noink option has no effect on Chrome mobile. It has the intended effect on Chrome desktop. I would be happy to just turn off the animations but noink has no effect.

I'm testing with a Nexus 4 running the latest Chrome mobile as of this posting: V48.0.2564.95.  It happens on other, more recent vintage devices, also.

**Comment by jptrainor** [comment] 2016-02-06 15:43
A simple work around is to use css to hide all paper-ripple in the element that contains the paper-radio-button elements.

```
paper-ripple {
      visibility: hidden;
    }

```

On mobile Chrome the entire radio button selection icon plus the label is highlighted momentarily when it is selected.  That highlight does not happen on the desktop.  Perhaps that highlight is interfering with the ripple effect (which is a small circle entered on the radio button selection icon).
- In my case I actually set the radio button's contained paper-ripple visibility to hidden by using javascript to set the style each time the radio button is selected... your mileage may vary.

**Comment by notwaldorf** [comment] 2016-02-08 21:23
What do you mean the animation doesn't complete? Do you mean that the focus state (which looks like an activate ripple) remains?

**Comment by jptrainor** [comment] 2016-02-08 22:21
I don't know if what I see can be described as the focus state or not.  It does appear that an "activated ripple" remains. It only happens on touch devices. I don't see it on desktop chrome.

I hide the paper-ripple to work around it. When hidden, I still a selection animation in the form of a transient rectangular highlight of the entire radio button including the label text - but it doesn't have the ripple effect, it just comes on then off.

I'll try to get a screen shot and post it.

**Comment by jptrainor** [comment] 2016-02-08 22:32
Et voila. Screen shot attached.  This it the paper-radio-button demo page.  See the noink demo section on the lower half of the page.  It shows the the lingering activated ripple, and also shows that the noink option is broken.  If you touch outside the button the lingering activated ripple will disappear. This was captured on a Moto G running up to date Android and Chrome.  Let me know if you need the version numbers.

![screenshot_2016-02-08-17-23-34](https://cloud.githubusercontent.com/assets/3492380/12901383/582ada4a-ce89-11e5-9df7-a11430aa88fd.png)

**Comment by JurgenKnops** [comment] 2016-02-17 21:22
Having the same problem...

Can also be reproduced on the paper-radio-button demo page with Chrome Desktop (48.0.2564.109) with Developer Tools and screen size emulation and/or touch screen emulation enabled.

Maybe relevant: in my application one of the paper-radio-buttons is putting focus to an input element, then the animation is 'ends' the correct because it 'loses' it's own focus.

**Comment by notwaldorf** [comment] 2016-02-19 18:24
This has the same root cause as https://github.com/PolymerElements/paper-button/issues/24, and should be fixed when that is fixed.

**Closed as completed by notwaldorf** 2016-02-19 18:24 UTC
Labels: pending-response

**Comment by RenatoUtsch** [comment] 2017-06-12 17:18
Why is this closed? This is still happening and making the paper-radio-button unusable.
